job: 
  include:
      - stage: test
        name: "Unit python test 3.4"
        language: python
        python:
          - 3.4
        script:
            - mkdir ShortStory
            - touch kkk
            - echo 5
      - # stage: test
        name: "Unit python test 2.7"
        language: python
        python:
          - 2.7
        script:
            - mkdir ShortStory
            - touch kkk
            - echo 5
      - stage: build
        name: "Just print anything"
        script: echo "This is the build stage"