job: 
  include:
      - stage: test
        language: python
        python:
          - 3.4
        script:
            - mkdir ShortStory
            - touch kkk
            - echo 5
      - # stage: test
        language: python
        python:
          - 2.7
        script:
            - mkdir ShortStory
            - touch kkk
            - echo 5
      - stage: build
        script: echo "This is the build stage"